AWSTemplateFormatVersion: '2010-09-09'
Description: Perf Monitor WebSocket stack
Parameters:
  ClusterName:
    Type: String
    Default: perf-monitor-cluster
  Image:
    Type: String
    Description: ECR image URI for WebSocket server
Resources:
  WsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref WsTask
  WsTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ContainerDefinitions:
        - Name: websocket
          Image: !Ref Image
          PortMappings:
            - ContainerPort: 4500
Outputs:
  ServiceName:
    Value: !Ref WsService

