version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: perf
      POSTGRES_PASSWORD: perf
      POSTGRES_DB: perfdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perf"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

